name: ToDoApp

trigger:
- main


stages:
    - stage: Build_and_Test
      displayName: Build and Test
      jobs:
        - job: build_and_test
          displayName: Build and Test
          pool:
              vmImage: 'ubuntu-latest'
          steps:
              - task: UsePythonVersion@0
                inputs:
                    versionSpec: 3.11
                displayName: Use Python 3.11
              - script: |
                    pip install --upgrade pip
                    pip install -r requirements.txt
                displayName: 'Installing dependencies'    
              - script: |
                  echo "Running tests..."
                  pytest
                displayName: "Run pytest"
                env:
                  MONGO_URI: $(MONGO_URI)  